### PR TITLE
Validate dataset before querying it

### LINKED ISSUE #59: Return validation results in dataset’s ontology
We now convert to DCAT first, then pass the result through SHACL. As a result of this, datasets in Schema.org will get a SHACL validation report based on DCAT, which can be confusing.

Therefore, try invert to invert the order and validate the dataset description before translating it to DCAT.

Empty JSON or a missing dataset seems to be allowed by SHACL (#58), so we’ll need to pre-validate against those cases.

### PR DESCRIPTION
**Pull request by ddeboer**
* First validate based on dereference, then query using SPARQL.
* Remove OPTIONALs from SPARQL query because we can now assume
  (at least one) valid dataset is available.
* Fix #59: return DCAT or Schema.org validation results based on dataset
  ontology.
* Ref #39: add automated validation test cases.
* Ref #18: test that new SHACL, which combines Schema and DCAT, is
  working properly.
* Reduce size of test data.

### CODE REVIEW

**Comment by ddeboer** [comment]
@coret Have a look at the test failures to see the things that currently aren’t working when using pure SHACL.

**Comment by coret** [comment]
Nice setup!

So currently two tests fail:
- Validator › rejects a list that contains at least one invalid Schema.org dataset : the test is wrong, line 38 should read the file datacatalog-schema-oa-one-invalid-dataset.jsonld (not datasets-schema-org-valid.jsonld)
- Validator › rejects empty JSON : this is correct, the SHACL validation is OK wil empty JSON, so an additional check should be added to the validation code to check for a least a dataset.

**Comment by ddeboer** [comment]
> Validator › rejects empty JSON : this is correct, the SHACL validation is OK wil empty JSON, so an additional check should be added to the validation code to check for at least one dataset.

Not empty JSON (RDF) but also RDF that is not a Dataset passes the SHACL while it shouldn’t.

**Comment by ddeboer** [comment]
> Validator › rejects empty JSON : this is correct, the SHACL validation is OK wil empty JSON, so an additional check should be added to the validation code to check for at least one dataset.

Correct. That check must support both `schema:` and `dcat:Dataset`.

**Pull request merged**
